### ISSUE TITLE
PinegaFV_Ревью ДЗ ОТУС рефлексия

### ISSUE THREAD

**Issue by FM102DX** [ZyuDev/Otus.CSharp.HW5#1]
Добрый день!

1) __Супер__, что все спрятано в 1 класс CsvSerializer<T>, и что он с дженериком. Это решает многие вопросы по юзабилити.

2) Порадовали аккуратно сделанные классы моделей, в частности реализованный ToString, равно как и сам сериализатор. Все понятно без комментов, ничего лишнего.

3) Минус, что в солюшене нет тестового примера, т.е. оно из коробки не работает, и в результате комментарии умозрительные, т.е. я не запускал сам код.

4) Также не увидел сравнения с аналогичными парсерами, например, от Newtonsoft

**Comment by ZyuDev** [comment]
Большое спасибо за review!

Тестовые примеры реализованы в виде тестового проекта 
https://github.com/ZyuDev/Otus.CSharp.HW5/tree/main/HW5.UnitTests

В том числе и нагрузочное тестирование и сравнение с Newtonsoft.
https://github.com/ZyuDev/Otus.CSharp.HW5/blob/main/HW5.UnitTests/SerializerFiveIntPerformanceTests.cs#L35
https://github.com/ZyuDev/Otus.CSharp.HW5/blob/main/HW5.UnitTests/SerializerFiveIntPerformanceTests.cs#L63
